notifications:
  email: false

sudo: true

language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - nvm install 13

before_script:
  - gem install awesome_bot

script:
  - ./run-tests.sh
